[base]
mode = "workspace"
smart_pull = true

[mode.workspace]
git_info = true
colorblind = false

[repositories]
repos = [
	"crs:amethyst",
	"crs:branding",
	"crs:caveman",
	"crs:crystal-docker",
	"crs:crystal-keyring",
	"crs:crystal-update",
	"crs:docs",
	"crs:getcryst.al",
	"crs:.github",
	"crs:grub-theme",
	"crs:iso", 
	"crs:jade", 
	"crs:jade-gui",
	"crs:jade-tui",
	"crs:malachite",
	"crs:moonstone",
	"crs:opal",
	"crs:pkg-warner",
	"crs:site",
	"crs:tourmaline",
	"crs:wallpapers",
	"crs:webforge",
	"mlc:pkgbuilds",
	"mlc:repos",
	"mlc:workspace",
]

[repositories.urls]
crs = "ssh://git@github.com/crystal-linux/{}"
mlc = "ssh://git@github.com/crystal-linux/mlc-{}"
